#ifndef F2C_SYMMAP_H
#define F2C_SYMMAP_H
#define br_prc_q__ br_prc_q_
#define bt_prc_q__ bt_prc_q_
#define dphi_b_rho0__ dphi_b_rho0_
#define igrf_to_cc___ igrf_to_cc__
#define mcos_t96_01___ mcos_t96_01__
#define r_s__ r_s_
#define rmco_bconic__ rmco_bconic_
#define rmco_bes0__ rmco_bes0_
#define rmco_bes1__ rmco_bes1_
#define rmco_bes__ rmco_bes_
#define rmco_birk1shld__ rmco_birk1shld_
#define rmco_birk1tot_02__ rmco_birk1tot_02_
#define rmco_birk2shl__ rmco_birk2shl_
#define rmco_birk2tot_02__ rmco_birk2tot_02_
#define rmco_birk_1n2__ rmco_birk_1n2_
#define rmco_birk_shl__ rmco_birk_shl_
#define rmco_birk_tot__ rmco_birk_tot_
#define rmco_circle__ rmco_circle_
#define rmco_condip1__ rmco_condip1_
#define rmco_crosslp__ rmco_crosslp_
#define rmco_cylhar1__ rmco_cylhar1_
#define rmco_cylharm__ rmco_cylharm_
#define rmco_deformed__ rmco_deformed_
#define rmco_dipdistr__ rmco_dipdistr_
#define rmco_diploop1__ rmco_diploop1_
#define rmco_dipole__ rmco_dipole_
#define rmco_dipole_tsy96__ rmco_dipole_tsy96_
#define rmco_dipshld__ rmco_dipshld_
#define rmco_dipxyz__ rmco_dipxyz_
#define rmco_extall__ rmco_extall_
#define rmco_fexp1__ rmco_fexp1_
#define rmco_fexp__ rmco_fexp_
#define rmco_ffs__ rmco_ffs_
#define rmco_fialcos__ rmco_fialcos_
#define rmco_full_rc__ rmco_full_rc_
#define rmco_intercon__ rmco_intercon_
#define rmco_loops4__ rmco_loops4_
#define rmco_magnetopause_2001__ rmco_magnetopause_2001_
#define rmco_one_cone__ rmco_one_cone_
#define rmco_prc_quad__ rmco_prc_quad_
#define rmco_prc_symm__ rmco_prc_symm_
#define rmco_r2_birk__ rmco_r2_birk_
#define rmco_r2inner__ rmco_r2inner_
#define rmco_r2outer__ rmco_r2outer_
#define rmco_r2sheet__ rmco_r2sheet_
#define rmco_rc_shield__ rmco_rc_shield_
#define rmco_rc_symm__ rmco_rc_symm_
#define rmco_ringcurr96__ rmco_ringcurr96_
#define rmco_shlcar3x3__ rmco_shlcar3x3_
#define rmco_shlcar3x3_tsy96__ rmco_shlcar3x3_tsy96_
#define rmco_shlcar5x5__ rmco_shlcar5x5_
#define rmco_src_prc__ rmco_src_prc_
#define rmco_t01_01_dbl__ rmco_t01_01_dbl_
#define rmco_tail87__ rmco_tail87_
#define rmco_taildisk__ rmco_taildisk_
#define rmco_taildisk_tsy96__ rmco_taildisk_tsy96_
#define rmco_tailrc96__ rmco_tailrc96_
#define rmco_tksi__ rmco_tksi_
#define rmco_twocones__ rmco_twocones_
#define rmco_unwarped__ rmco_unwarped_
#define rmco_warped__ rmco_warped_
#define rmco_xksi__ rmco_xksi_
#define t01_01___ t01_01__
#define t89___ t89__
#define t89_boberg___ t89_boberg__
#define t89c___ t89c__
#define t89c_boberg___ t89c_boberg__
#define theta_s__ theta_s_
#define where_in_magnetopause2001__ where_in_magnetopause2001_
#endif
